sudo: true # required until https://github.com/travis-ci/travis-ci/issues/9069 gets resolved
dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: osx
      osx_image: xcode7.3
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=2.7
    - os: osx
      osx_image: xcode7.3
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.6
    - os: osx
      osx_image: xcode7.3
      language: objective-c
      env: TRAVIS_PYTHON_VERSION=3.7
before_install:
  - df -h
  - date
  - pwd
  - uname -a
  - source tools/travis_section_def.sh
  - source tools/travis_before_install.sh
  - which python; python --version
  - tools/build_versions.py
install:
  - section build
  - python setup.py clean
  - python setup.py build_ext -i
  - section_end build
script: tools/travis.sh
notifications:
  email:
    on_success: change
    on_failure: change
