[project]
name = "lap"
description = "Linear Assignment Problem solver (LAPJV/LAPMOD)"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["lapjv", "lapmod", "linear assignment problem"]
authors = [{name = "Tomas Kazmar", email = "tomash.kazmar@seznam.cz"}]
version = "0.5dev"
license = {file = "LICENSE"}
classifiers = [
	"Development Status :: 4 - Beta",
	"Environment :: Console",
	"Intended Audience :: Science/Research",
	"Intended Audience :: Developers",
	"Programming Language :: C",
	"Programming Language :: Python",
	"Programming Language :: Python :: 3.8",
	"Programming Language :: Python :: 3.9",
	"Programming Language :: Python :: 3.10",
	"Programming Language :: Python :: 3.11",
	"Operating System :: Microsoft :: Windows",
	"Operating System :: POSIX",
	"Operating System :: Unix",
	"Operating System :: MacOS",
]
dependencies = ["numpy"]

[project.optional-dependencies]
dev = ["build", "wheel", "cython", "tox"]
test = ["pytest", "pytest-timeout"]

[build-system]
requires = ["setuptools", "numpy"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
# https://docs.pytest.org/en/7.3.x/explanation/goodpractices.html#which-import-mode
addopts = [
    "--import-mode=importlib",
]

[tool.tox]
legacy_tox_ini = """
  [tox]
    min_version = 4.0

    [testenv]
    extras = test
    commands = pytest
"""
