name: PyPI Build

on: [workflow_dispatch]

jobs:

  # # # # # # # # # # # # # # # # # # # # #
  # Windows jobs
  # # # # # # # # # # # # # # # # # # # # #

  build_windows:
    name: Build windows (Python 3.8-3.14)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==3.3.1
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp38-* cp314-*"
          CIBW_SKIP: "*-win32 pp*"
          CIBW_ARCHS_WINDOWS: "AMD64 ARM64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: windows-all-wheels
          path: ./wheelhouse/*.whl

  build_windows_p37:
    name: Build windows (Python 3.7)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.23.3
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp37-*"
          CIBW_SKIP: "*-win32 pp*"
          CIBW_ARCHS_WINDOWS: "AMD64 ARM64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: windows-all-p37-wheels
          path: ./wheelhouse/*.whl

  # # # # # # # # # # # # # # # # # # # # #
  # macOS jobs
  # # # # # # # # # # # # # # # # # # # # #

  build_macos_intel:
    name: Build macos-intel (Python 3.8-3.14)
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==3.3.1
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp38-* cp314-*"
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_MACOS: "x86_64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: macos-intel-wheels
          path: ./wheelhouse/*.whl

  build_macos_intel_p37:
    name: Build macos-intel (Python 3.7)
    runs-on: macos-15-intel
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.23.3
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp37-*"
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_MACOS: "x86_64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: macos-intel-p37-wheels
          path: ./wheelhouse/*.whl

  build_macos_arm:
    name: Build macos-arm (Python 3.8-3.14)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==3.3.1
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp38-* cp314-*"
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_MACOS: "arm64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm-wheels
          path: ./wheelhouse/*.whl

  # # # # # # # # # # # # # # # # # # # # #
  # Linux jobs
  # # # # # # # # # # # # # # # # # # # # #

  build_linux_intel:
    name: Build linux-intel (Python 3.8-3.14)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==3.3.1
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp38-* cp314-*"
          CIBW_SKIP: "*-manylinux_i686 pp*"
          CIBW_ARCHS_LINUX: "x86_64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: linux-intel-wheels
          path: ./wheelhouse/*.whl

  build_linux_intel_p37:
    name: Build linux-intel (Python 3.7)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.23.3
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp37-*"
          CIBW_SKIP: "*-manylinux_i686 pp*"
          CIBW_ARCHS_LINUX: "x86_64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: linux-intel-p37-wheels
          path: ./wheelhouse/*.whl

  build_linux_arm:
    name: Build linux-arm (Python 3.8-3.14)
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==3.3.1
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp38-* cp314-*"
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_LINUX: "aarch64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm-wheels
          path: ./wheelhouse/*.whl

  build_linux_arm_p37:
    name: Build linux-arm (Python 3.7)
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install cibuildwheel
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.23.3
      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD_VERBOSITY: 1
          CIBW_BUILD: "cp37-*"
          CIBW_SKIP: "pp*"
          CIBW_ARCHS_LINUX: "aarch64"
      - name: Archive wheels
        uses: actions/upload-artifact@v4
        with:
          name: linux-arm-p37-wheels
          path: ./wheelhouse/*.whl

  # # # # # # # # # # # # # # # # # # # # #
  # Source dist job
  # # # # # # # # # # # # # # # # # # # # #

  build_source:
    name: Build source dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install "setuptools>=67.8.0"
          pip install wheel build
      - name: Build .tar.gz
        run: python -m build --sdist
      - name: Archive .tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: source-dist
          path: dist/*.tar.gz
